### PR TITLE
fix: only merge non-enumerable global properties that are not in VM scope

### LINKED ISSUE #29: ReferenceError: __webpack_require__ is not defined
Hi!

We've been debugging the issue https://github.com/seek-oss/vanilla-extract/issues/637 over at the vanilla-extract repository and it seems that the recent 0.1.7 version introduced a regression causing webpack to fail.

For now this is "fixed" by pinning to an older version: https://github.com/seek-oss/vanilla-extract/pull/639

Thanks for creating and maintaining this library!

### PR DESCRIPTION
**Pull request by Josh-Cena**
Follow-up of #27. Fix #29

Case as where #27 failed:

```js
new vm.Script("globalThis.Prism = 1; console.log(Prism)").runInNewContext({ globalThis });
```

Because the `globalThis` in this case is an exotic object, the latter `Prism` isn't actually made a "global".

```js
new vm.Script("console.log({} instanceof Object)").runInNewContext({ console, Object });
```

Logs `false` because `Object` is exotic. Removing `Object` from the scope causes it to log `true`.

The resolution is to filter out anything that's already in the VM scope.

cc @pierrec This is a hotfix.
cc @slorber FYI

### CODE REVIEW

File: eval.js [hunk 1]
```diff
@@ -5,16 +5,18 @@ var requireLike = require('require-like')
...
   for (var k, i = 0, n = keys.length; i < n; i++) {
     k = keys[i]
     a[k] = b[k]
   }
   return a
 }
 
+var vmGlobals = new vm.Script('vmGlobals = Object.getOwnPropertyNames(globalThis)')
+  .runInNewContext()
+  .vmGlobals
```
Comment (slorber) [inline eval.js]:
```suggestion
```

This leads to an issue to me, globals are directly accessible in my case? 🤷‍♂️

File: eval.js [hunk 2]
```diff
@@ -5,16 +5,18 @@ var requireLike = require('require-like')
...
-  var keys = Object.getOwnPropertyNames(b)
+  var keys = Object.keys(b)
   for (var k, i = 0, n = keys.length; i < n; i++) {
     k = keys[i]
     a[k] = b[k]
   }
   return a
 }
 
+var vmGlobals = new vm.Script('vmGlobals = Object.getOwnPropertyNames(globalThis)')
```
Comment (slorber) [inline eval.js]: Review hint:

- 👍 eager call but only takes > 1ms for my mac

- List is:

```js
[
  "Object",
  "Function",
  "Array",
  "Number",
  "parseFloat",
  "parseInt",
  "Infinity",
  "NaN",
  "undefined",
  "Boolean",
  "String",
  "Symbol",
  "Date",
  "Promise",
  "RegExp",
  "Error",
  "AggregateError",
  "EvalError",
  "RangeError",
  "ReferenceError",
  "SyntaxError",
  "TypeError",
  "URIError",
  "globalThis",
  "JSON",
  "Math",
  "console",
  "Intl",
  "ArrayBuffer",
  "Uint8Array",
  "Int8Array",
  "Uint16Array",
  "Int16Array",
  "Uint32Array",
  "Int32Array",
  "Float32Array",
  "Float64Array",
  "Uint8ClampedArray",
  "BigUint64Array",
  "BigInt64Array",
  "DataView",
  "Map",
  "BigInt",
  "Set",
  "WeakMap",
  "WeakSet",
  "Proxy",
  "Reflect",
  "FinalizationRegistry",
  "WeakRef",
  "decodeURI",
  "decodeURIComponent",
  "encodeURI",
  "encodeURIComponent",
  "escape",
  "unescape",
  "eval",
  "isFinite",
  "isNaN",
  "SharedArrayBuffer",
  "Atomics",
  "WebAssembly",
];

```

File: eval.js [hunk 3]
```diff
@@ -37,7 +39,19 @@ module.exports = function (content, filename, scope, includeGlobals) {
...
+    // Merge enumerable variables on `global`
     merge(sandbox, global)
+    // Merge all non-enumerable variables on `global`, including console (v10+),
+    // process (v12+), URL, etc. We first filter out anything that's already in
+    // the VM scope (i.e. those in the ES standard) so we don't have two copies
+    Object.getOwnPropertyNames(global).forEach((name) => {
+      if (!vmGlobals.includes(name)) {
+        sandbox[name] = global[name]
+      }
+    })
```
Comment (slorber) [inline eval.js:50]: Review hint

New globals automatically forwarded:

```js
[
  "global",
  "process",
  "Buffer",
  "atob",
  "btoa",
  "URL",
  "URLSearchParams",
  "TextEncoder",
  "TextDecoder",
  "AbortController",
  "AbortSignal",
  "EventTarget",
  "Event",
  "MessageChannel",
  "MessagePort",
  "MessageEvent",
  "clearInterval",
  "clearTimeout",
  "setInterval",
  "setTimeout",
  "queueMicrotask",
  "performance",
  "clearImmediate",
  "setImmediate",
  "__extends",
  "__assign",
  "__rest",
  "__decorate",
  "__param",
  "__metadata",
  "__awaiter",
  "__generator",
  "__exportStar",
  "__createBinding",
  "__values",
  "__read",
  "__spread",
  "__spreadArrays",
  "__spreadArray",
  "__await",
  "__asyncGenerator",
  "__asyncDelegator",
  "__asyncValues",
  "__makeTemplateObject",
  "__importStar",
  "__importDefault",
  "__classPrivateFieldGet",
  "__classPrivateFieldSet",
  "consola",
  "regeneratorRuntime",
];
```

**Review by slorber — APPROVED** [review]
👍 looks like a better solution to me

would still be useful to allow excluding some globals?

File: eval.js (hunk 3 above)
Comment (Josh-Cena) [reply eval.js:50]: Most of these globals are injected by the transpiler. Only stuff like `URL` `process` `TextDecoder` etc. are of our interest.

**Comment by Josh-Cena** [comment]
> would still be useful to allow excluding some globals?

I don't think that's necessarily the goal of this module and I frankly can't see how that's useful😅 Since we have a forked SSG plugin, if you really want to exclude some globals, just use `includeGlobals=false` and use the more verbose `scope` instead. WDYT?
